about:
    access: restricted
    footnote: nll
    grain: ''
    groups:
    - null
    license: ckdbl
    processed: ''
    remote: ''
    rights: public
    source: ''
    space: ''
    subject: ''
    summary: Pre-k Enrollment for 3 and 4 year olds
    tags: []
    time: ''
    title: Pre-k Enrollment for 3 and 4 year olds
contacts:
    wrangler:
        email: eric@civicknowledge.com
        name: Eric Busboom
        org: Civic Knowledge
        url: http://civicknowledge.com
external_documentation: {}
identity:
    btime: p5ye2014
    dataset: acs
    id: d05i
    revision: 1
    source: census.gov
    subset: enrollment
    variation: hdp
    version: 0.0.1
names:
    fqname: census.gov-acs-p5ye2014-hdp-0.0.1~d05i001
    name: census.gov-acs-p5ye2014-hdp
    vid: d05i001
    vname: census.gov-acs-p5ye2014-hdp-0.0.1
pipelines:
    build:
        select_partition:
            - SelectPartitionFromSource
    build-combined:
        select_partition:
            - SelectPartition("bundle.select_county_partition(source, row)")
    build-combined_cols:
        select_partition:
            - SelectPartition("bundle.select_county_cols_partition(source, row)")
